function [data, auxData, metaData, txtData, weights] = mydata_Sebastes_fasciatus
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Perciformes';
metaData.family     = 'Sebastidae';
metaData.species    = 'Sebastes_fasciatus';
metaData.species_en = 'Acadian redfish';

metaData.ecoCode.climate = {'Dfb','Dfc'};
metaData.ecoCode.ecozone = {'MANW'};
metaData.ecoCode.habitat = {'bjFe','0iM','0iMc','bpMcd','bpMd'};
metaData.ecoCode.embryo  = {'Mv'};
metaData.ecoCode.migrate = {'Mo'};
metaData.ecoCode.food    = {'bxPz','bpCi','jpCik','jiCvf'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(5); % K, body temp

metaData.data_0     = {'ab','tp','am','Lb','Lp','Li','Ww0','Wwp','Wwi','Ri','ab','am','Lh','Lb','Lp','Lpm','Li','Ri'};
metaData.data_1     = {};

metaData.COMPLETE   = 1; % using criteria of LikaKear2011

metaData.author     = {'Joelle Guitard'};
metaData.date_subm  = [2023 6 6];
metaData.email      = {'joelle.guitard@uqar.ca'};
metaData.address    = {};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight@tecnico.ulisboa.pt'};
metaData.date_acc   = [2023 6 6];

%% set zero-variate data
data.ab = 8; units.ab = 'd'; label.ab = 'age at birth'; bibkey.ab = {'Gasc2003'};
  temp.ab = C2K(6.9); units.temp.ab = 'K'; label.temp.ab = 'temperature';
  comment.ab = 'Guessed by Corine';
data.am = 18250; units.am = 'd'; label.am = 'life span'; bibkey.am = {'Gasc2003'};
  temp.am = C2K(6); units.temp.am = 'K'; label.temp.am = 'temperature';

data.Lh = 0.6; units.Lh = 'cm'; label.Lh = 'length at hatch'; bibkey.Lh = {'Tani1961'};
data.Lb = 0.84; units.Lb = 'cm'; label.Lb = 'length at birth'; bibkey.Lb = {'Burn2020'};
data.Lp = 16.26; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = {'Brul2023'};
data.Lpm = 15.91; units.Lpm = 'cm'; label.Lpm = 'length at puberty for males'; bibkey.Lpm = {'Brul2023'};
data.Li = 50; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = {'Gasc2003'};

data.Ri = 293; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = {'Gasc2003'};
  temp.Ri = C2K(6); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = 'per year';

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Links
metaData.links.id_CoL = '4W7M3'; % Cat of Life
metaData.links.id_EoL = '46568110'; % Ency of Life
metaData.links.id_Wiki = 'Sebastes_fasciatus'; % Wikipedia
metaData.links.id_ADW = 'Sebastes_fasciatus'; % Anim Div. Web
metaData.links.id_Taxo = '187273'; % Taxonomicon
metaData.links.id_WoRMS = '127252';
metaData.links.id_fishbase = 'Sebastes-fasciatus';

%% References
bibkey = 'Brul2023'; type = 'techreport'; bib = [ ...
'author = {Brûlé Caroline, Benhalima Kadra, Roux Marie-Julie, Parent Geneviève, Chavarria Caroline, Senay Caroline}, ' ... 
'title = {Updating knowledge of Redfish (Sebastes mentella and S. fasciatus) reproduction in a changing environment, the Gulf of St. Lawrence and Laurentian Channel, Canada}, ' ... 
'institution = {Oceans and Fisheries Canada}, ' ... 
'year = {2023}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Burn2020'; type = 'article'; bib = [ ...
'author = {Burns, Corinne M.; Lauzon, Félix; Plourde, Stéphane; Sirois, Pascal; Robert, Dominique}, ' ... 
'title = {Interannual variability of diet composition and prey preference of larval redfish (Sebastes spp.) in the Gulf of St. Lawrence}, ' ... 
'journal = {Journal of Plankton Research}, ' ... 
'year = {2020}, ' ... 
'volume = {42}, ' ... 
'pages = {581-594}, ' ... 
'doi = {10.1093/plankt/fbaa040}, ' ... 
'howpublished = {\url{https://www.mendeley.com/catalogue/f0b5bf7e-3ef2-3a93-a591-3df5286f3f5c/?utm_source=desktop&utm_medium=1.19.8&utm_campaign=open_catalog&userDocumentId=%7B732b440f-980a-42b0-8825-3ec7be2254a4%7D}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Gasc2003'; type = 'article'; bib = [ ...
'author = {Dominique Gascon}, ' ... 
'title = {Redfish Multidisciplinary Research Zonal Program (1995-1998): Final Report}, ' ... 
'journal = {Canadian Technical Report of Fisheries and Aquatic Sciences}, ' ... 
'year = {2003}, ' ... 
'volume = {2462}, ' ... 
'pages = {155}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Penn1985'; type = 'article'; bib = [ ...
'author = {R.W. Penney; G.T.Evans}, ' ... 
'title = {Growth histories of larval redfish (Sebastes spp.) on an offshore Atlantic fishing Bank determined by otolith increment analysis.}, ' ... 
'journal = {Canadian journal of fisheries and aquatic sciences}, ' ... 
'year = {1985}, ' ... 
'volume = {42}, ' ... 
'pages = {1452-1464}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Tani1961'; type = 'techreport'; bib = [ ...
'author = {A. V. Taning}, ' ... 
'title = {Larval and postlarval stages of Sebastes species and Helicolenus dactylopterus.}, ' ... 
'institution = {Conseil International pour l’Exploration de la Mer}, ' ... 
'year = {1961}, ' ... 
'volume = {150}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
