function [data, auxData, metaData, txtData, weights] = mydata_Sebastes_fasciatus_individual
% file generated by prt_mydata
global n_ind
n_ind = 12;

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Perciformes';
metaData.family     = 'Sebastidae';
metaData.species    = 'Sebastes_fasciatus';
metaData.species_en = 'Acadian redfish, individuals';

metaData.ecoCode.climate = {'Dfb','Dfc'};
metaData.ecoCode.ecozone = {'MANW'};
metaData.ecoCode.habitat = {'bjFe','0iM','0iMc','bpMcd','bpMd'};
metaData.ecoCode.embryo  = {'Mv'};
metaData.ecoCode.migrate = {'Mo'};
metaData.ecoCode.food    = {'bxPz','bpCi','jpCik','jiCvf'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(5); % K, body temp

metaData.data_0     = {'ab','tp','am','Lb','Lp','Li','Ww0','Wwp','Wwi','Ri','ab','am','Lh','Lb','Lp','Lpm','Li','Ri'};
metaData.data_1     = {};

metaData.COMPLETE   = 1; % using criteria of LikaKear2011

metaData.author     = {'Joelle Guitard'};
metaData.date_subm  = [2023 6 6];
metaData.email      = {'joelle.guitard@uqar.ca'};
metaData.address    = {};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight@tecnico.ulisboa.pt'};
metaData.date_acc   = [2023 6 6];
  

% 
indNames = {
    'ind 1','ind 2','ind 3','ind 4','ind 5','ind 6', 'ind 7', 'ind 8',...
    'ind 9', 'ind 10','ind 11','ind 12'
    };
% ,'ind 13','ind 14', 'ind 15', 'ind 16', ...
%     'ind 17', 'ind 18','ind 19','ind 20'
%     };
% 
% uni-variate data
cd ../

%%%Uni-variate for 2.5 deg C
data.tL2 = readmatrix('t-L_2.5_pivotlength2.5.csv');
data.tL2 = [data.tL2(:,1), data.tL2(:,2:n_ind+1)./10]; % d, mm to cm
units.tL2 = {'d', 'cm'}; label.tL2 = {'time', 'length'};  bibkey.tL2 = {'Sena2021'};
temp.tL2 = C2K(2.5); units.temp.tL2 = 'K'; label.temp.tL2 = 'temperature';
Lwstart.tL2 =  data.tL2(1,2:n_ind); units.Lwstart.tL2 = 'cm'; label.Lwstart.tL2 = 'initial length';
treat.tL2 = {1, indNames};

data.tW2 = readmatrix('t-Ww_2.5_pivotweights2.5.csv');
data.tW2 = [data.tW2(:,1), data.tW2(:,2:n_ind+1)]; % d, g
units.tW2 = {'d', 'g'}; label.tW2 = {'time', 'wet weight'};  bibkey.tW2 = {'Sena2021'};
temp.tW2 = C2K(2.5); units.temp.tW2 = 'K'; label.temp.tW2 = 'temperature';
treat.tW2 = {1, indNames};
Lw0.tL2 = data.tL2(1,2:end); units.Lw0.tL2 = 'cm'; label.Lw0.tL2 = 'initial length';


% %%%Uni-variate for 7.5 deg C
% data.tL7 = readmatrix('t-L_7.5_pivotlength7.5.csv');
% data.tL7 = [data.tL7(:,1), data.tL7(:,2:n_ind+1)./10]; % d, mm to cm
% units.tL7 = {'d', 'cm'}; label.tL7 = {'time', 'length'};  bibkey.tL7 = {'Sena2021'};
% temp.tL7 = C2K(7.5); units.temp.tL7 = 'K'; label.temp.tL7 = 'temperature';
% Lwstart.tL7 =  data.tL7(1,2:n_ind); units.Lwstart.tL7 = 'cm'; label.Lwstart.tL7 = 'initial length';
% treat.tL7 = {1, indNames};
% Lw0.tL7 = data.tL7(1,2:end); units.Lw0.tL7 = 'cm'; label.Lw0.tL7 = 'initial length';
% 
% 
% data.tW7 = readmatrix('t-Ww_7.5_pivotweights7.5.csv');
% data.tW7 = [data.tW7(:,1), data.tW7(:,2:n_ind+1)]; % d, g
% units.tW7 = {'d', 'g'}; label.tW7 = {'time', 'wet weight'};  bibkey.tW7 = {'Sena2021'};
% temp.tW7 = C2K(7.5); units.temp.tW7 = 'K'; label.temp.tW7 = 'temperature';
% treat.tW7 = {1, indNames};
% 
% 
% %%%Uni-variate for 5
% data.tL5 = readmatrix('t-L_5.0_pivotlength5.0.csv');
% data.tL5 = [data.tL5(:,1), data.tL5(:,2:n_ind+1)./10]; % d, mm to cm
% units.tL5 = {'d', 'cm'}; label.tL5 = {'time', 'length'};  bibkey.tL5 = {'Sena2021'};
% temp.tL5 = C2K(5); units.temp.tL5 = 'K'; label.temp.tL5 = 'temperature';
% Lwstart.tL5 =  data.tL5(1,2:n_ind); units.Lwstart.tL5 = 'cm'; label.Lwstart.tL5 = 'initial length';
% treat.tL5 = {1, indNames}; % 1- plot together
% Lw0.tL5 = data.tL5(1,2:end); units.Lw0.tL5 = 'cm'; label.Lw0.tL5 = 'initial length';
% 
% data.tW5 = readmatrix('t_Ww_5.0_pivotweights5.0.csv');
% data.tW5 = [data.tW5(:,1), data.tW5(:,2:n_ind+1)]; % d, g
% units.tW5 = {'d', 'g'}; label.tW5 = {'time', 'wet weight'};  bibkey.tW5 = {'Sena2021'};
% temp.tW5 = C2K(5); units.temp.tW5 = 'K'; label.temp.tW5 = 'temperature';
% treat.tW5 = {1, indNames};
% 
% 
% %%% 10 deg C
% data.tL10 = readmatrix('t-L_10.0_pivotlength10.0.csv');
% data.tL10 = [data.tL10(:,1), data.tL10(:,2:n_ind+1)./10]; % d, mm to cm
% units.tL10 = {'d', 'cm'}; label.tL10 = {'time', 'length'};  bibkey.tL10 = {'Sena2021'};
% temp.tL10 = C2K(10); units.temp.tL10 = 'K'; label.temp.tL10 = 'temperature';
% Lwstart.tL10 =  data.tL10(1,2:n_ind+1); units.Lwstart.tL10 = 'cm'; label.Lwstart.tL10 = 'initial length';
% treat.tL10 = {1, indNames};
% Lw0.tL10 = data.tL10(1,2:end); units.Lw0.tL10 = 'cm'; label.Lw0.tL10 = 'initial length';
% 
% 
% data.tW10 = readmatrix('t_Ww_10.0_pivotweights10.0.csv');
% data.tW10 = [data.tW10(:,1), data.tW10(:,2:n_ind+1)]; % d, g
% units.tW10 = {'d', 'g'}; label.tW10 = {'time', 'wet weight'};  bibkey.tW10 = {'Sena2021'};
% temp.tW10 = C2K(10); units.temp.tW10 = 'K'; label.temp.tW10 = 'temperature';
% treat.tW10 = {1, indNames};

cd Sebastes_fasciatus_ind


%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
auxData.Lw0 = Lw0;
auxData.treat = treat;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
 
%% Discussion points
D1 = 'individuals assumed to differ by p_Am (z in this construct)';
metaData.discussion = struct('D1', D1);


%% References
bibkey = 'Brul2023'; type = 'techreport'; bib = [ ...
'author = {Brûlé Caroline, Benhalima Kadra, Roux Marie-Julie, Parent Geneviève, Chavarria Caroline, Senay Caroline}, ' ... 
'title = {Updating knowledge of Redfish (Sebastes mentella and S. fasciatus) reproduction in a changing environment, the Gulf of St. Lawrence and Laurentian Channel, Canada}, ' ... 
'institution = {Oceans and Fisheries Canada}, ' ... 
'year = {2023}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Burn2020'; type = 'article'; bib = [ ...
'author = {Burns, Corinne M.; Lauzon, Félix; Plourde, Stéphane; Sirois, Pascal; Robert, Dominique}, ' ... 
'title = {Interannual variability of diet composition and prey preference of larval redfish (Sebastes spp.) in the Gulf of St. Lawrence}, ' ... 
'journal = {Journal of Plankton Research}, ' ... 
'year = {2020}, ' ... 
'volume = {42}, ' ... 
'pages = {581-594}, ' ... 
'doi = {10.1093/plankt/fbaa040}, ' ... 
'howpublished = {\url{https://www.mendeley.com/catalogue/f0b5bf7e-3ef2-3a93-a591-3df5286f3f5c/?utm_source=desktop&utm_medium=1.19.8&utm_campaign=open_catalog&userDocumentId=%7B732b440f-980a-42b0-8825-3ec7be2254a4%7D}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Gasc2003'; type = 'article'; bib = [ ...
'author = {Dominique Gascon}, ' ... 
'title = {Redfish Multidisciplinary Research Zonal Program (1995-1998): Final Report}, ' ... 
'journal = {Canadian Technical Report of Fisheries and Aquatic Sciences}, ' ... 
'year = {2003}, ' ... 
'volume = {2462}, ' ... 
'pages = {155}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Penn1985'; type = 'article'; bib = [ ...
'author = {R.W. Penney; G.T.Evans}, ' ... 
'title = {Growth histories of larval redfish (Sebastes spp.) on an offshore Atlantic fishing Bank determined by otolith increment analysis.}, ' ... 
'journal = {Canadian journal of fisheries and aquatic sciences}, ' ... 
'year = {1985}, ' ... 
'volume = {42}, ' ... 
'pages = {1452-1464}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'Tani1961'; type = 'techreport'; bib = [ ...
'author = {A. V. Taning}, ' ... 
'title = {Larval and postlarval stages of Sebastes species and Helicolenus dactylopterus.}, ' ... 
'institution = {Conseil International pour l’Exploration de la Mer}, ' ... 
'year = {1961}, ' ... 
'volume = {150}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
